import Head from "next/head";
import Layout from "../Components/Layouts";
import Hero from "../Components/Hero";
import Services from "../Components/Services"
import css from '../styles/Home.module.css'
export default function Home() {
  return (
    <Layout>
      <div className={css.container}>
        <Head>
          <title>FUDO</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        {/* body */}
        <main>
          <Hero />
          <Services />
        </main>
      </div>
    </Layout>
  );
}
